version: '3.8'

services:
  blogapp:
    build: .
    container_name: blogapp
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Prevents overwriting node_modules

    command: npm run dev
    depends_on:
      - mysql # Wait for mysql to be ready
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123@
      DB_NAME: blogdb

  mysql:
    image: mysql:8
    container_name: mysql-container-2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123@
      MYSQL_DATABASE: blogdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

    